server:
  port: 8075

spring:
  application:
    name: eureka-zipkin
  zipkin:
    base-url: http://localhost:8075
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false
