server:
  port: 8077

spring:
  application:
    name: springcloud-admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 暴露的api
        include: health,info