server:
  port: 8078

spring:
  application:
    name: springcloud-client
  boot:
    admin:
      client:
        url: http://localhost:8077
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/